### ISSUE TITLE
(not an issue) for the last few days ive been working on polymer

### ISSUE THREAD

**Issue by CodeDiseaseDev** [atxi/Polymer#11]
for the last few days ive been working on polymer, and i'd like to show you what im doing with it (this is just a personal project because i want to learn more about 3d rendering)

![image](https://github.com/atxi/Polymer/assets/70626250/b128b03a-3282-47ef-8784-777711e8f12a)

physics are half implemented, temporary entity renderer (cubes only for now) (also renders players with their usernames), temporary attack button 'E' to attack entities around you within 5 blocks, local client-side commands for debugging

coming: pause menu to adjust settings on the fly with your mouse, full physics and collision detection so that the player cant phase through blocks

ive learned heaps from this lil side-project, i finally (mostly) understand 3d -> 2d projection

**Comment by atxi** [comment]
Oh cool, nice work. Adding menu settings sounds like a decent amount of work unless you decide to use something like Nuklear or Dear ImGui. I guess some simple dragging operations wouldn't be too difficult without those.

It would probably be a lot easier to learn that stuff with a different project because polymer is kind of brittle and probably poorly put together. I never used Vulkan before starting this project, so I had no idea what I was doing. The renderer doesn't really support useful rendering operations other than the texture arrays if I recall correctly.

**Comment by CodeDiseaseDev** [comment]
![image](https://github.com/atxi/Polymer/assets/70626250/a4c39642-8278-4ee9-bed1-ebef07b6a6a1)
i plan on making something similar to my direct2d gui framework just for the pause menu and stuff :)

**Comment by CodeDiseaseDev** [comment]
also yeah i have 0 clue how vulkan works so this whole time ive been using font_renderer for all the HUD stuff lool,
i tried making it separate but i just couldnt wrap my head around how vulkan works

**Comment by CodeDiseaseDev** [comment]
so ALL of the 3d cubes are just drawn with font_renderer
