### ISSUE TITLE
Game crashes with a "Failed to connect" error

### ISSUE THREAD

**Issue by nac5604** [atxi/Polymer#12]
I tried running the polymer.exe file; it shows a white window, then crashes and spits out this error. I've tried to connect using a different port, but I get the same result.

```
PS C:\Users\Administrator\Downloads\polymer> .\polymer.exe -u polymer -s 127.0.0.1:25565
Polymer: Windows
Asset time: 382.968994
Connecting to '127.0.0.1:25565' with username 'believer'.
Failed to connect
```

**Comment by nac5604** [comment]
Also, is there a discord/telegram/guilded/matrix for the project? I would very much like to follow the development and ask questions there.

**Comment by atxi** [comment]
Are you running a server and connecting to the correct ip and port? This is just a client that connects to a Java Minecraft server. It closes because it's not getting a connection to that server. I never got around to implementing a menu for managing the server connection actions.

There's no place for discussion for the project because this was just a toy project that I was working on for fun. This client only got far enough to connect to offline mode servers and render the chunks, so there's not much to really discuss.

You can check out [wiki.vg](https://wiki.vg/Client_List) if you're interested in following clients that are further along in development.
