### ISSUE TITLE
Low FPS on first build & debug

### ISSUE THREAD

**Issue by ryuujo1573** [atxi/Polymer#5]
Hi, I'm interested in your nice work, and I've tried `polymer.exe` from releases.
The client worked fine and was running like, 1k+ fps.

Later I tried to build the polymer exec on my own, so I configured cmake and build target as provided instructions.
But the console was flushing with some warning outputs, and it was 10fps or lower...

What was wrong? (log attached)

https://pastebin.com/1VhhZu3w

**Comment by atxi** [comment]
The main problem seems to be that you were building it in Debug mode. That will always be way slower. If you're using MSVC to compile it, make sure you set it to Release x64 build mode in the toolbar.

I'm not sure why you were getting validation errors, but those won't show up in Release mode. I'll have to look into image creation because I don't get those validation errors on my machine. I might just be using an old SDK version that doesn't have up to date validation checks.

**Comment by atxi** [comment]
It seems like your graphics card doesn't support the format that I set as the preferred format. I just pushed a commit that might get rid of the validation errors, but I think it will result in bad looking mipmapping if you don't have the correct format still.

It's hard to work on issues like this because every graphics card supports different formats.

**Comment by ryuujo1573** [comment]
Thanks for your reply, I'll try asap

**Comment by powerbute** [comment]
Hello, the same problem when I launch from the release I get 1k + FPS, but self-assembly 30-60 FPS. What can fix this?

**Comment by powerbute** [comment]
In order for the fps to stand and not fall, we just removed it from the Vulkan config.
C:\Users\User\AppData\Local\LunarG\vkconfig\override\VkLayer_override.json
Before:
https://pastebin.com/NWxdZ9jg
After:
https://pastebin.com/s0FeigcC

**Comment by atxi** [comment]
Thanks for the update.

That validation override is controlled by the Vulkan Configurator that came with the Vulkan SDK. By default, it shouldn't be overriding layers unless that specific checkbox was selected. I guess it's possible that both of you selected it without knowing or you just left the configurator running after the SDK installed. If you left it running, it will override the layers by default.

Anyone who has the same issue can fix it by opening Vulkan Configurator in the start menu and making sure Layers Fully Controlled by the Vulkan Applications is selected. It's important to disable it because it could affect the performance of any game/program using Vulkan on your computer.
